### ISSUE TITLE
No domains that worked issue is back

### ISSUE THREAD

**Issue by ubercracker8977** [markop159/Markop159-repository#7]
This issue has returned again on version 1.7.5

Any ideas?

**Comment by Napsty** [comment]
It's probably because a new version 1.7.6 needs to be released first. The PopCornTime API Servers needed to be migrated, see https://www.reddit.com/r/PopCornTime/comments/g13vcq/read_this_if_popcorn_time_doesnt_load_any_content/
The necessary changes of the API were already done in https://github.com/markop159/KODI-Popcorn-Time/pull/125 and merged to master, but the repository needs to publish the new version, too.

**Comment by ubercracker8977** [comment]
I just SSH'ed into the Kodi and fixed the two files here:
https://github.com/markop159/KODI-Popcorn-Time/pull/125/files
Changed .website to .sh  - done - very simple fix.  

SSH into your Kodi
nano /storage/.kodi/addons/plugin.video.kodipopcorntime/resources/lib/kodipopcorntime/favourites.py
change line 144 
from: search = '%s/movie/%s' % ('https://tv-v2.api-fetch.website', fav['id'])
To:     search = '%s/movie/%s' % ('https://tv-v2.api-fetch.sh', fav['id'])

Save the file

nano /storage/.kodi/addons/plugin.video.kodipopcorntime/resources/lib/kodipopcorntime/providers/api-fetch.py
Change Line 30 
from: "https://tv-v2.api-fetch.website"
to:      "https://tv-v2.api-fetch.sh"

Save the file

All done... enjoy!

**Comment by Klootjavaan** [comment]
Thank you ubercracker8977, works fine now 🙌

**Comment by Powershellder** [comment]
True, the changes work well. Now lets hope we manage to get an updated version for it to :P

**Comment by Kevsosmooth** [comment]
Once I extract the file on my pc and edit the python script and save it then recompress it does not let me add the file.

I am not sure why it is not working.

**Comment by Kevsosmooth** [comment]
After I edit the python script and try to run the zip file again into kodi with the newly associated file. It gives me an error

![image](https://user-images.githubusercontent.com/11496433/81360219-446ba700-90a9-11ea-910c-cdaf1955128f.png)

**Comment by datavistics** [comment]
> I just SSH'ed into the Kodi and fixed the two files here:

I used termux to ssh, but I was unable to see those files.

**Comment by sorin-pop** [comment]
Can't believe it takes so long to properly release such an important fix... well, I guess that's how it is in the world of open source software. Things get sloppy.

**Comment by Tonio101** [comment]
@ubercracker8977 Awesome, thanks for the patch!

**Comment by daniel3xxx** [comment]
You guys can download 1.7.6 from here:
https://github.com/markop159/Markop159-repository/blob/3e11afd10a974d4038d94258ac9600859fd7c69b/Releases/plugin.video.kodipopcorntime/plugin.video.kodipopcorntime-1.7.6.zip
It was submited on 3rd of May but since then no answer from Markop159

**Comment by srlorddark** [comment]
> It's probably because a new version 1.7.6 needs to be released first. The PopCornTime API Servers needed to be migrated, see https://www.reddit.com/r/PopCornTime/comments/g13vcq/read_this_if_popcorn_time_doesnt_load_any_content/
> The necessary changes of the API were already done in [markop159/KODI-Popcorn-Time#125](https://github.com/markop159/KODI-Popcorn-Time/pull/125) and merged to master, but the repository needs to publish the new version, too.

It works fine now, thanks!

**Comment by ubercracker8977** [comment]
This issue is back because https://tv-v2.api-fetch.sh is down.  Using my above instructions posted April 16, 2020 just change the following:
from:  https://tv-v2.api-fetch.sh

To:  http://popcorn-ru.tk

Cheers!!!

**Comment by MihaiChirculete** [comment]
> I just SSH'ed into the Kodi and fixed the two files here:
> https://github.com/markop159/KODI-Popcorn-Time/pull/125/files
> Changed .website to .sh - done - very simple fix.
> 
> SSH into your Kodi
> nano /storage/.kodi/addons/plugin.video.kodipopcorntime/resources/lib/kodipopcorntime/favourites.py
> change line 144
> from: search = '%s/movie/%s' % ('https://tv-v2.api-fetch.website', fav['id'])
> To: search = '%s/movie/%s' % ('http://popcorn-ru.tk', fav['id'])
> 
> Save the file
> 
> nano /storage/.kodi/addons/plugin.video.kodipopcorntime/resources/lib/kodipopcorntime/providers/api-fetch.py
> Change Line 30
> from: "https://tv-v2.api-fetch.website"
> to: "http://popcorn-ru.tk"
> 
> Save the file
> 
> All done... enjoy!

This fix is no longer working

**Comment by tonycastle** [comment]
http://popcorn-ru.tk/ seems to be dead, is there an alternative?

**Comment by lubo** [comment]
What do you mean? The website works, you can see on their GitHub that it's actively developed.

**Comment by tonycastle** [comment]
> What do you mean? The website works, you can see on their GitHub that it's actively developed.

I was talking about the domain, It was down for a while yesterday but it is back up again.

**Comment by tonycastle** [comment]
So this is finally dead now right?  - the http://popcorn-ru.tk/  domain has gone or is there a new domain to connect to?
